from __future__ import annotations

from datetime import datetime
from typing import Any, Iterable, Mapping, Protocol, runtime_checkable

from .models import (
    CatalogCredentials,
    Download,
    DownloadEvent,
    DownloadJob,
    Episode,
    FeedFetchResult,
    FeedValidators,
    HttpResponse,
    InputEvent,
    ParsedFeed,
    Playback,
    PlaybackEvent,
    PlaybackSource,
    Podcast,
    RequestPolicy,
)


class Clock(Protocol):
    def now_utc(self) -> datetime: ...


class MonotonicClock(Protocol):
    def seconds(self) -> float: ...


class PodcastCatalog(Protocol):
    def categories(self) -> list[str]: ...
    def search(self, query: str, limit: int) -> list[Podcast]: ...
    def podcast(self, feed_id: int) -> Podcast | None: ...


class HttpTransport(Protocol):
    def request(self, policy: RequestPolicy, url: str, headers: Mapping[str, str]) -> HttpResponse: ...


class FeedReader(Protocol):
    def fetch(self, url: str, validators: FeedValidators) -> FeedFetchResult: ...
    def parse(self, body: bytes, source_url: str) -> ParsedFeed: ...


class PodcastRepository(Protocol):
    def save(self, podcast: Podcast) -> None: ...
    def get(self, podcast_id: str) -> Podcast | None: ...
    def list_subscribed(self) -> list[Podcast]: ...


class EpisodeRepository(Protocol):
    def upsert(self, episode: Episode) -> Episode: ...
    def get(self, episode_id: str) -> Episode | None: ...
    def list_for_podcast(self, podcast_id: str) -> list[Episode]: ...


class PlaybackRepository(Protocol):
    def save(self, playback: Playback) -> None: ...
    def get(self, episode_id: str) -> Playback | None: ...


class DownloadRepository(Protocol):
    def save(self, download: Download) -> None: ...
    def get(self, episode_id: str) -> Download | None: ...
    def delete(self, episode_id: str) -> None: ...


class SettingsRepository(Protocol):
    def get(self, key: str) -> str | None: ...
    def set(self, key: str, value: str) -> None: ...


class AtomicFilePort(Protocol):
    def write_atomic(self, relative_path: str, data: bytes) -> None: ...
    def read_bytes(self, relative_path: str) -> bytes: ...
    def exists(self, relative_path: str) -> bool: ...
    def size(self, relative_path: str) -> int: ...
    def unlink(self, relative_path: str) -> None: ...


@runtime_checkable
class InputSource(Protocol):
    def poll(self) -> list[InputEvent]: ...


class FeedPreviewReader(Protocol):
    def preview(self, url: str) -> Podcast: ...


class ConnectivityProbe(Protocol):
    def is_online(self) -> bool: ...


class CredentialProvider(Protocol):
    def podcast_index(self) -> CatalogCredentials | None: ...


class Logger(Protocol):
    def info(self, message: str, *, extra: Mapping[str, Any] | None = None) -> None: ...


StructuredLogger = Logger


class DownloadRunner(Protocol):
    def start(self, job: DownloadJob) -> None: ...
    def cancel(self, episode_id: str) -> None: ...
    def events(self) -> Iterable[DownloadEvent]: ...


class PlaybackEngine(Protocol):
    def play(self, source: PlaybackSource, start_seconds: float) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def seek(self, position_seconds: float) -> None: ...
    def stop(self) -> None: ...
    def events(self) -> Iterable[PlaybackEvent]: ...
    def shutdown(self) -> None: ...


class EventSource(Protocol):
    def events(self) -> Iterable[Any]: ...
